use_frameworks!

platform :ios, '8.0'

target 'LXCAlertController_Example' do
  pod 'LXCAlertController', :path => '../'

  target 'LXCAlertController_Tests' do
    inherit! :search_paths

    
  end
end
